const products = [
  {
    _id: "1",
    name: "YSL Satin Sandals",
    category: "Shoes",
    color: "black",
    image: "/frontend/public/images/YSL shoes.jpeg",
    price: 1350,
    countInStock: 2,
    brand: "YSL",
    rating: 4.5,
    numReviews: 10,
    description: "Squared toe sandals with rhinestones buckle straps",
  },

  {
    _id: "2",
    name: "Christian Louboutin So Kate",
    category: "Shoes",
    color: "black",
    image: "../public/images/Louboutins.jpeg",
    price: 695,
    countInStock: 10,
    brand: "Christian Louboutin",
    rating: 5,
    numReviews: 20,
    description: "120 mm Pumps - Patent calf leather",
  },
  {
    _id: "3",
    name: "Jimmy Choo Averly 100",
    color: "white",
    image: "../public/images/AVERLY100YMG_080933_ANGLE_vg01.webp",
    description: "Latte Pumps with Asymmetric Grosgrain Mesh Fascinator Bows",
    category: "Shoes",
    price: 895,
    countInStock: 3,
    brand: "Jimmy Choo",
    rating: 5,
    numReviews: 7,
  },

  {
    _id: "4",
    name: "Manolo Blahnik Satin Pumps",
    category: "Shoes",
    color: "blue",
    image: "../public/images/AVERLY100YMG_080933_ANGLE_vg01.jpeg",
    price: 1075,
    countInStock: 1,
    brand: "Manolo",
    rating: 4.0,
    numReviews: 4,
    description: "Hangisi 105 embellished satin pumps",
  },
];

export default products;
